# automatically generated by the FlatBuffers compiler, do not modify

# namespace: PluginManager

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Plugin(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Plugin()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPlugin(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Plugin
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Plugin
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Plugin
    def Title(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Plugin
    def Description(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Plugin
    def Author(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Plugin
    def DateCreated(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Plugin
    def DateModified(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Plugin
    def IconUrl(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Plugin
    def Category(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Plugin
    def Downloads(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Plugin
    def Follows(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Plugin
    def Url(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Plugin
    def Source(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def PluginStart(builder):
    builder.StartObject(12)

def Start(builder):
    PluginStart(builder)

def PluginAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def AddName(builder, name):
    PluginAddName(builder, name)

def PluginAddTitle(builder, title):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(title), 0)

def AddTitle(builder, title):
    PluginAddTitle(builder, title)

def PluginAddDescription(builder, description):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(description), 0)

def AddDescription(builder, description):
    PluginAddDescription(builder, description)

def PluginAddAuthor(builder, author):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(author), 0)

def AddAuthor(builder, author):
    PluginAddAuthor(builder, author)

def PluginAddDateCreated(builder, dateCreated):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(dateCreated), 0)

def AddDateCreated(builder, dateCreated):
    PluginAddDateCreated(builder, dateCreated)

def PluginAddDateModified(builder, dateModified):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(dateModified), 0)

def AddDateModified(builder, dateModified):
    PluginAddDateModified(builder, dateModified)

def PluginAddIconUrl(builder, iconUrl):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(iconUrl), 0)

def AddIconUrl(builder, iconUrl):
    PluginAddIconUrl(builder, iconUrl)

def PluginAddCategory(builder, category):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(category), 0)

def AddCategory(builder, category):
    PluginAddCategory(builder, category)

def PluginAddDownloads(builder, downloads):
    builder.PrependInt32Slot(8, downloads, 0)

def AddDownloads(builder, downloads):
    PluginAddDownloads(builder, downloads)

def PluginAddFollows(builder, follows):
    builder.PrependInt32Slot(9, follows, 0)

def AddFollows(builder, follows):
    PluginAddFollows(builder, follows)

def PluginAddUrl(builder, url):
    builder.PrependUOffsetTRelativeSlot(10, flatbuffers.number_types.UOffsetTFlags.py_type(url), 0)

def AddUrl(builder, url):
    PluginAddUrl(builder, url)

def PluginAddSource(builder, source):
    builder.PrependUOffsetTRelativeSlot(11, flatbuffers.number_types.UOffsetTFlags.py_type(source), 0)

def AddSource(builder, source):
    PluginAddSource(builder, source)

def PluginEnd(builder):
    return builder.EndObject()

def End(builder):
    return PluginEnd(builder)
